// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelPendingPayment(arg1:string):Promise<void>;

export function CreatePayment(arg1:models.BoldPaymentRequest):Promise<models.BoldPaymentResponse>;

export function CreatePaymentWithContext(arg1:models.BoldPaymentRequest,arg2:number,arg3:string,arg4:number,arg5:number,arg6:number,arg7:number):Promise<models.BoldPaymentResponse>;

export function CreatePendingPayment(arg1:models.BoldPendingPayment):Promise<void>;

export function CreateTerminal(arg1:models.BoldTerminal):Promise<void>;

export function DeleteTerminal(arg1:number):Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetAllTerminals():Promise<Array<models.BoldTerminal>>;

export function GetBoldConfig():Promise<models.BoldConfig>;

export function GetPaymentMethods():Promise<Array<models.BoldPaymentMethod>>;

export function GetPendingPayment(arg1:string):Promise<models.BoldPendingPayment>;

export function GetPendingPaymentStatus(arg1:string):Promise<string>;

export function GetRecentWebhooks(arg1:number):Promise<Array<models.BoldPendingPayment>>;

export function GetTerminals():Promise<Array<models.BoldTerminalResponse>>;

export function GetWebhookLogs(arg1:number):Promise<Array<models.BoldWebhookLog>>;

export function SyncTerminals():Promise<void>;

export function TestConnection():Promise<void>;

export function UpdateBoldConfig(arg1:models.BoldConfig):Promise<void>;

export function UpdateTerminal(arg1:models.BoldTerminal):Promise<void>;
