// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePayment(arg1) {
  return window['go']['services']['BoldService']['CreatePayment'](arg1);
}

export function CreateTerminal(arg1) {
  return window['go']['services']['BoldService']['CreateTerminal'](arg1);
}

export function DeleteTerminal(arg1) {
  return window['go']['services']['BoldService']['DeleteTerminal'](arg1);
}

export function GetAPIKey() {
  return window['go']['services']['BoldService']['GetAPIKey']();
}

export function GetAllTerminals() {
  return window['go']['services']['BoldService']['GetAllTerminals']();
}

export function GetBoldConfig() {
  return window['go']['services']['BoldService']['GetBoldConfig']();
}

export function GetPaymentMethods() {
  return window['go']['services']['BoldService']['GetPaymentMethods']();
}

export function GetTerminals() {
  return window['go']['services']['BoldService']['GetTerminals']();
}

export function SyncTerminals() {
  return window['go']['services']['BoldService']['SyncTerminals']();
}

export function TestConnection() {
  return window['go']['services']['BoldService']['TestConnection']();
}

export function UpdateBoldConfig(arg1) {
  return window['go']['services']['BoldService']['UpdateBoldConfig'](arg1);
}

export function UpdateTerminal(arg1) {
  return window['go']['services']['BoldService']['UpdateTerminal'](arg1);
}
