// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreatePayment(arg1:models.BoldPaymentRequest):Promise<models.BoldPaymentResponse>;

export function CreateTerminal(arg1:models.BoldTerminal):Promise<void>;

export function DeleteTerminal(arg1:number):Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetAllTerminals():Promise<Array<models.BoldTerminal>>;

export function GetBoldConfig():Promise<models.BoldConfig>;

export function GetPaymentMethods():Promise<Array<models.BoldPaymentMethod>>;

export function GetTerminals():Promise<Array<models.BoldTerminalResponse>>;

export function SyncTerminals():Promise<void>;

export function TestConnection():Promise<void>;

export function UpdateBoldConfig(arg1:models.BoldConfig):Promise<void>;

export function UpdateTerminal(arg1:models.BoldTerminal):Promise<void>;
