// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemToCombo(arg1, arg2, arg3) {
  return window['go']['services']['ComboService']['AddItemToCombo'](arg1, arg2, arg3);
}

export function Create(arg1) {
  return window['go']['services']['ComboService']['Create'](arg1);
}

export function CreateCombo(arg1) {
  return window['go']['services']['ComboService']['CreateCombo'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['ComboService']['Delete'](arg1, arg2);
}

export function DeleteCombo(arg1) {
  return window['go']['services']['ComboService']['DeleteCombo'](arg1);
}

export function EnsureDB() {
  return window['go']['services']['ComboService']['EnsureDB']();
}

export function ExpandComboToOrderItems(arg1, arg2) {
  return window['go']['services']['ComboService']['ExpandComboToOrderItems'](arg1, arg2);
}

export function Find(arg1, arg2) {
  return window['go']['services']['ComboService']['Find'](arg1, arg2);
}

export function First(arg1, arg2) {
  return window['go']['services']['ComboService']['First'](arg1, arg2);
}

export function GetAllCombos() {
  return window['go']['services']['ComboService']['GetAllCombos']();
}

export function GetAllCombosAdmin() {
  return window['go']['services']['ComboService']['GetAllCombosAdmin']();
}

export function GetCombo(arg1) {
  return window['go']['services']['ComboService']['GetCombo'](arg1);
}

export function GetCombosByCategory(arg1) {
  return window['go']['services']['ComboService']['GetCombosByCategory'](arg1);
}

export function GetDB() {
  return window['go']['services']['ComboService']['GetDB']();
}

export function Model(arg1) {
  return window['go']['services']['ComboService']['Model'](arg1);
}

export function Preload(arg1) {
  return window['go']['services']['ComboService']['Preload'](arg1);
}

export function RemoveItemFromCombo(arg1, arg2) {
  return window['go']['services']['ComboService']['RemoveItemFromCombo'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['services']['ComboService']['Save'](arg1);
}

export function SetDB(arg1) {
  return window['go']['services']['ComboService']['SetDB'](arg1);
}

export function ToggleComboActive(arg1) {
  return window['go']['services']['ComboService']['ToggleComboActive'](arg1);
}

export function UpdateCombo(arg1) {
  return window['go']['services']['ComboService']['UpdateCombo'](arg1);
}

export function UpdateComboItemQuantity(arg1, arg2) {
  return window['go']['services']['ComboService']['UpdateComboItemQuantity'](arg1, arg2);
}

export function Where(arg1, arg2) {
  return window['go']['services']['ComboService']['Where'](arg1, arg2);
}

export function WithTransaction(arg1) {
  return window['go']['services']['ComboService']['WithTransaction'](arg1);
}
