// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {gorm} from '../models';

export function AddItemToCombo(arg1:number,arg2:number,arg3:number):Promise<models.Combo>;

export function Create(arg1:any):Promise<void>;

export function CreateCombo(arg1:models.Combo):Promise<models.Combo>;

export function Delete(arg1:any,arg2:number):Promise<void>;

export function DeleteCombo(arg1:number):Promise<void>;

export function EnsureDB():Promise<void>;

export function ExpandComboToOrderItems(arg1:number,arg2:number):Promise<Array<services.ExpandedOrderItem>>;

export function Find(arg1:any,arg2:Array<any>):Promise<void>;

export function First(arg1:any,arg2:Array<any>):Promise<void>;

export function GetAllCombos():Promise<Array<models.Combo>>;

export function GetAllCombosAdmin():Promise<Array<models.Combo>>;

export function GetCombo(arg1:number):Promise<models.Combo>;

export function GetCombosByCategory(arg1:number):Promise<Array<models.Combo>>;

export function GetDB():Promise<gorm.DB>;

export function Model(arg1:any):Promise<gorm.DB>;

export function Preload(arg1:string):Promise<gorm.DB>;

export function RemoveItemFromCombo(arg1:number,arg2:number):Promise<models.Combo>;

export function Save(arg1:any):Promise<void>;

export function SetDB(arg1:gorm.DB):Promise<void>;

export function ToggleComboActive(arg1:number):Promise<models.Combo>;

export function UpdateCombo(arg1:models.Combo):Promise<models.Combo>;

export function UpdateComboItemQuantity(arg1:number,arg2:number):Promise<void>;

export function Where(arg1:any,arg2:Array<any>):Promise<gorm.DB>;

export function WithTransaction(arg1:any):Promise<void>;
