// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckExistingConfig(arg1) {
  return window['go']['services']['ConfigManagerService']['CheckExistingConfig'](arg1);
}

export function CompleteSetup() {
  return window['go']['services']['ConfigManagerService']['CompleteSetup']();
}

export function ConfigExists() {
  return window['go']['services']['ConfigManagerService']['ConfigExists']();
}

export function CreateDefaultConfig() {
  return window['go']['services']['ConfigManagerService']['CreateDefaultConfig']();
}

export function CreateDefaultData() {
  return window['go']['services']['ConfigManagerService']['CreateDefaultData']();
}

export function GetConfig() {
  return window['go']['services']['ConfigManagerService']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['services']['ConfigManagerService']['GetConfigPath']();
}

export function InitializeDatabase(arg1) {
  return window['go']['services']['ConfigManagerService']['InitializeDatabase'](arg1);
}

export function IsFirstRun() {
  return window['go']['services']['ConfigManagerService']['IsFirstRun']();
}

export function SaveConfig(arg1) {
  return window['go']['services']['ConfigManagerService']['SaveConfig'](arg1);
}

export function SaveRestaurantConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['ConfigManagerService']['SaveRestaurantConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['services']['ConfigManagerService']['TestDatabaseConnection'](arg1);
}
