// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePrinterConfig(arg1) {
  return window['go']['services']['ConfigService']['DeletePrinterConfig'](arg1);
}

export function GetAllSystemConfigs() {
  return window['go']['services']['ConfigService']['GetAllSystemConfigs']();
}

export function GetDIANConfig() {
  return window['go']['services']['ConfigService']['GetDIANConfig']();
}

export function GetDIANParametricData() {
  return window['go']['services']['ConfigService']['GetDIANParametricData']();
}

export function GetDatabaseConfig() {
  return window['go']['services']['ConfigService']['GetDatabaseConfig']();
}

export function GetDefaultPrinter() {
  return window['go']['services']['ConfigService']['GetDefaultPrinter']();
}

export function GetPrinterConfigs() {
  return window['go']['services']['ConfigService']['GetPrinterConfigs']();
}

export function GetRestaurantConfig() {
  return window['go']['services']['ConfigService']['GetRestaurantConfig']();
}

export function GetSyncConfig() {
  return window['go']['services']['ConfigService']['GetSyncConfig']();
}

export function GetSystemConfig(arg1) {
  return window['go']['services']['ConfigService']['GetSystemConfig'](arg1);
}

export function GetSystemConfigBool(arg1, arg2) {
  return window['go']['services']['ConfigService']['GetSystemConfigBool'](arg1, arg2);
}

export function GetSystemConfigInt(arg1, arg2) {
  return window['go']['services']['ConfigService']['GetSystemConfigInt'](arg1, arg2);
}

export function GetTableLayout() {
  return window['go']['services']['ConfigService']['GetTableLayout']();
}

export function GetUITheme() {
  return window['go']['services']['ConfigService']['GetUITheme']();
}

export function GetWebSocketPort() {
  return window['go']['services']['ConfigService']['GetWebSocketPort']();
}

export function InitializeDefaultConfig() {
  return window['go']['services']['ConfigService']['InitializeDefaultConfig']();
}

export function InitializeDefaultSystemConfigs() {
  return window['go']['services']['ConfigService']['InitializeDefaultSystemConfigs']();
}

export function SavePrinterConfig(arg1) {
  return window['go']['services']['ConfigService']['SavePrinterConfig'](arg1);
}

export function SaveTableLayout(arg1) {
  return window['go']['services']['ConfigService']['SaveTableLayout'](arg1);
}

export function SetSystemConfig(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ConfigService']['SetSystemConfig'](arg1, arg2, arg3, arg4);
}

export function SetWebSocketPort(arg1) {
  return window['go']['services']['ConfigService']['SetWebSocketPort'](arg1);
}

export function UpdateDIANConfig(arg1) {
  return window['go']['services']['ConfigService']['UpdateDIANConfig'](arg1);
}

export function UpdateRestaurantConfig(arg1) {
  return window['go']['services']['ConfigService']['UpdateRestaurantConfig'](arg1);
}

export function UpdateSyncConfig(arg1) {
  return window['go']['services']['ConfigService']['UpdateSyncConfig'](arg1);
}

export function UpdateUITheme(arg1) {
  return window['go']['services']['ConfigService']['UpdateUITheme'](arg1);
}

export function ValidateConfiguration() {
  return window['go']['services']['ConfigService']['ValidateConfiguration']();
}
