// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeletePrinterConfig(arg1:number):Promise<void>;

export function GetAllSystemConfigs():Promise<Array<models.SystemConfig>>;

export function GetDIANConfig():Promise<models.DIANConfig>;

export function GetDIANParametricData():Promise<models.DIANParametricData>;

export function GetDatabaseConfig():Promise<Record<string, string>>;

export function GetDefaultPrinter():Promise<models.PrinterConfig>;

export function GetPrinterConfigs():Promise<Array<models.PrinterConfig>>;

export function GetRestaurantConfig():Promise<models.RestaurantConfig>;

export function GetSyncConfig():Promise<models.SyncConfig>;

export function GetSystemConfig(arg1:string):Promise<string>;

export function GetTableLayout():Promise<models.TableLayout>;

export function GetUITheme():Promise<models.UITheme>;

export function GetWebSocketPort():Promise<number>;

export function InitializeDefaultConfig():Promise<void>;

export function SavePrinterConfig(arg1:models.PrinterConfig):Promise<void>;

export function SaveTableLayout(arg1:models.TableLayout):Promise<void>;

export function SetSystemConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetWebSocketPort(arg1:number):Promise<void>;

export function UpdateDIANConfig(arg1:models.DIANConfig):Promise<void>;

export function UpdateRestaurantConfig(arg1:models.RestaurantConfig):Promise<void>;

export function UpdateSyncConfig(arg1:models.SyncConfig):Promise<void>;

export function UpdateUITheme(arg1:models.UITheme):Promise<void>;

export function ValidateConfiguration():Promise<boolean|Array<string>>;
