// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTunnelOutput() {
  return window['go']['services']['ConfigService']['ClearTunnelOutput']();
}

export function Create(arg1) {
  return window['go']['services']['ConfigService']['Create'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['ConfigService']['Delete'](arg1, arg2);
}

export function DeletePrinterConfig(arg1) {
  return window['go']['services']['ConfigService']['DeletePrinterConfig'](arg1);
}

export function DownloadCloudflared() {
  return window['go']['services']['ConfigService']['DownloadCloudflared']();
}

export function EnsureDB() {
  return window['go']['services']['ConfigService']['EnsureDB']();
}

export function Find(arg1, arg2) {
  return window['go']['services']['ConfigService']['Find'](arg1, arg2);
}

export function First(arg1, arg2) {
  return window['go']['services']['ConfigService']['First'](arg1, arg2);
}

export function GetAllSystemConfigs() {
  return window['go']['services']['ConfigService']['GetAllSystemConfigs']();
}

export function GetDB() {
  return window['go']['services']['ConfigService']['GetDB']();
}

export function GetDIANConfig() {
  return window['go']['services']['ConfigService']['GetDIANConfig']();
}

export function GetDIANParametricData() {
  return window['go']['services']['ConfigService']['GetDIANParametricData']();
}

export function GetDatabaseConfig() {
  return window['go']['services']['ConfigService']['GetDatabaseConfig']();
}

export function GetDefaultPrinter() {
  return window['go']['services']['ConfigService']['GetDefaultPrinter']();
}

export function GetNetworkConfig() {
  return window['go']['services']['ConfigService']['GetNetworkConfig']();
}

export function GetPrinterConfigs() {
  return window['go']['services']['ConfigService']['GetPrinterConfigs']();
}

export function GetRestaurantConfig() {
  return window['go']['services']['ConfigService']['GetRestaurantConfig']();
}

export function GetSystemConfig(arg1) {
  return window['go']['services']['ConfigService']['GetSystemConfig'](arg1);
}

export function GetSystemConfigBool(arg1, arg2) {
  return window['go']['services']['ConfigService']['GetSystemConfigBool'](arg1, arg2);
}

export function GetSystemConfigInt(arg1, arg2) {
  return window['go']['services']['ConfigService']['GetSystemConfigInt'](arg1, arg2);
}

export function GetTableLayout() {
  return window['go']['services']['ConfigService']['GetTableLayout']();
}

export function GetTunnelConfig() {
  return window['go']['services']['ConfigService']['GetTunnelConfig']();
}

export function GetTunnelConfigDB() {
  return window['go']['services']['ConfigService']['GetTunnelConfigDB']();
}

export function GetTunnelDownloadURL() {
  return window['go']['services']['ConfigService']['GetTunnelDownloadURL']();
}

export function GetTunnelStatus() {
  return window['go']['services']['ConfigService']['GetTunnelStatus']();
}

export function GetUITheme() {
  return window['go']['services']['ConfigService']['GetUITheme']();
}

export function GetWebSocketPort() {
  return window['go']['services']['ConfigService']['GetWebSocketPort']();
}

export function InitializeDefaultConfig() {
  return window['go']['services']['ConfigService']['InitializeDefaultConfig']();
}

export function InitializeDefaultSystemConfigs() {
  return window['go']['services']['ConfigService']['InitializeDefaultSystemConfigs']();
}

export function IsTunnelInstalled() {
  return window['go']['services']['ConfigService']['IsTunnelInstalled']();
}

export function Model(arg1) {
  return window['go']['services']['ConfigService']['Model'](arg1);
}

export function Preload(arg1) {
  return window['go']['services']['ConfigService']['Preload'](arg1);
}

export function Save(arg1) {
  return window['go']['services']['ConfigService']['Save'](arg1);
}

export function SaveNetworkConfig(arg1) {
  return window['go']['services']['ConfigService']['SaveNetworkConfig'](arg1);
}

export function SavePrinterConfig(arg1) {
  return window['go']['services']['ConfigService']['SavePrinterConfig'](arg1);
}

export function SaveTableLayout(arg1) {
  return window['go']['services']['ConfigService']['SaveTableLayout'](arg1);
}

export function SaveTunnelConfigDB(arg1) {
  return window['go']['services']['ConfigService']['SaveTunnelConfigDB'](arg1);
}

export function SetDB(arg1) {
  return window['go']['services']['ConfigService']['SetDB'](arg1);
}

export function SetSystemConfig(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ConfigService']['SetSystemConfig'](arg1, arg2, arg3, arg4);
}

export function SetTunnelConfig(arg1) {
  return window['go']['services']['ConfigService']['SetTunnelConfig'](arg1);
}

export function SetWebSocketPort(arg1) {
  return window['go']['services']['ConfigService']['SetWebSocketPort'](arg1);
}

export function StartQuickTunnel(arg1) {
  return window['go']['services']['ConfigService']['StartQuickTunnel'](arg1);
}

export function StartTunnelWithToken(arg1) {
  return window['go']['services']['ConfigService']['StartTunnelWithToken'](arg1);
}

export function StopTunnel() {
  return window['go']['services']['ConfigService']['StopTunnel']();
}

export function UpdateDIANConfig(arg1) {
  return window['go']['services']['ConfigService']['UpdateDIANConfig'](arg1);
}

export function UpdateRestaurantConfig(arg1) {
  return window['go']['services']['ConfigService']['UpdateRestaurantConfig'](arg1);
}

export function UpdateUITheme(arg1) {
  return window['go']['services']['ConfigService']['UpdateUITheme'](arg1);
}

export function ValidateConfiguration() {
  return window['go']['services']['ConfigService']['ValidateConfiguration']();
}

export function Where(arg1, arg2) {
  return window['go']['services']['ConfigService']['Where'](arg1, arg2);
}

export function WithTransaction(arg1) {
  return window['go']['services']['ConfigService']['WithTransaction'](arg1);
}
