// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CompleteSetup():Promise<void>;

export function ConfigExists():Promise<boolean>;

export function CreateDefaultConfig():Promise<config.AppConfig>;

export function GetConfig():Promise<config.AppConfig>;

export function GetConfigPath():Promise<string>;

export function InitializeDatabase(arg1:config.DatabaseConfig):Promise<void>;

export function IsFirstRun():Promise<boolean>;

export function RunSeeds():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function TestDatabaseConnection(arg1:config.DatabaseConfig):Promise<void>;
