// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProductToPage(arg1, arg2, arg3) {
  return window['go']['services']['CustomPageService']['AddProductToPage'](arg1, arg2, arg3);
}

export function CreatePage(arg1) {
  return window['go']['services']['CustomPageService']['CreatePage'](arg1);
}

export function DeletePage(arg1) {
  return window['go']['services']['CustomPageService']['DeletePage'](arg1);
}

export function GetAllPages() {
  return window['go']['services']['CustomPageService']['GetAllPages']();
}

export function GetPage(arg1) {
  return window['go']['services']['CustomPageService']['GetPage'](arg1);
}

export function GetPageWithProducts(arg1) {
  return window['go']['services']['CustomPageService']['GetPageWithProducts'](arg1);
}

export function RemoveProductFromPage(arg1, arg2) {
  return window['go']['services']['CustomPageService']['RemoveProductFromPage'](arg1, arg2);
}

export function SetPageProducts(arg1, arg2) {
  return window['go']['services']['CustomPageService']['SetPageProducts'](arg1, arg2);
}

export function UpdatePage(arg1) {
  return window['go']['services']['CustomPageService']['UpdatePage'](arg1);
}
