// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddProductToPage(arg1:number,arg2:number,arg3:number):Promise<void>;

export function CreatePage(arg1:models.CustomPage):Promise<void>;

export function DeletePage(arg1:number):Promise<void>;

export function GetAllPages():Promise<Array<models.CustomPage>>;

export function GetPage(arg1:number):Promise<models.CustomPage>;

export function GetPageWithProducts(arg1:number):Promise<Array<models.Product>>;

export function RemoveProductFromPage(arg1:number,arg2:number):Promise<void>;

export function SetPageProducts(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdatePage(arg1:models.CustomPage):Promise<void>;
