// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveTables() {
  return window['go']['services']['DashboardService']['GetActiveTables']();
}

export function GetDashboardStats() {
  return window['go']['services']['DashboardService']['GetDashboardStats']();
}

export function GetLowStockProducts() {
  return window['go']['services']['DashboardService']['GetLowStockProducts']();
}

export function GetPendingOrdersDetails() {
  return window['go']['services']['DashboardService']['GetPendingOrdersDetails']();
}

export function GetSalesChartData(arg1) {
  return window['go']['services']['DashboardService']['GetSalesChartData'](arg1);
}
