// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function ChangeEnvironment(arg1:string):Promise<void>;

export function ConfigureCertificate():Promise<void>;

export function ConfigureCompany():Promise<Record<string, any>>;

export function ConfigureCreditNoteResolution():Promise<void>;

export function ConfigureDebitNoteResolution():Promise<void>;

export function ConfigureResolution():Promise<void>;

export function ConfigureSoftware():Promise<void>;

export function GetDIANConfig():Promise<models.DIANConfig>;

export function GetNumberingRanges():Promise<Record<string, any>>;

export function MigrateToProduction():Promise<void>;

export function ResetConfigurationSteps():Promise<void>;

export function SendInvoice(arg1:services.DIANInvoice):Promise<services.DIANInvoiceResponse>;

export function TestConnection():Promise<void>;

export function UpdateDIANConfig(arg1:models.DIANConfig):Promise<void>;
