// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function ChangeEnvironment(arg1:string):Promise<void>;

export function ConfigureCertificate():Promise<void>;

export function ConfigureCompany(arg1:services.DIANCompanyConfig):Promise<void>;

export function ConfigureResolution():Promise<void>;

export function ConfigureSoftware():Promise<void>;

export function GetDIANConfig():Promise<models.DIANConfig>;

export function GetNumberingRanges():Promise<Record<string, any>>;

export function TestConnection():Promise<void>;

export function UpdateDIANConfig(arg1:models.DIANConfig):Promise<void>;
