// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeEnvironment(arg1) {
  return window['go']['services']['DIANService']['ChangeEnvironment'](arg1);
}

export function ConfigureCertificate() {
  return window['go']['services']['DIANService']['ConfigureCertificate']();
}

export function ConfigureCompany() {
  return window['go']['services']['DIANService']['ConfigureCompany']();
}

export function ConfigureCreditNoteResolution() {
  return window['go']['services']['DIANService']['ConfigureCreditNoteResolution']();
}

export function ConfigureDebitNoteResolution() {
  return window['go']['services']['DIANService']['ConfigureDebitNoteResolution']();
}

export function ConfigureLogo() {
  return window['go']['services']['DIANService']['ConfigureLogo']();
}

export function ConfigureResolution() {
  return window['go']['services']['DIANService']['ConfigureResolution']();
}

export function ConfigureSoftware() {
  return window['go']['services']['DIANService']['ConfigureSoftware']();
}

export function GetDIANConfig() {
  return window['go']['services']['DIANService']['GetDIANConfig']();
}

export function GetNextConsecutive(arg1, arg2) {
  return window['go']['services']['DIANService']['GetNextConsecutive'](arg1, arg2);
}

export function GetNumberingRanges() {
  return window['go']['services']['DIANService']['GetNumberingRanges']();
}

export function GetResolutionLimitStatus() {
  return window['go']['services']['DIANService']['GetResolutionLimitStatus']();
}

export function MigrateToProduction() {
  return window['go']['services']['DIANService']['MigrateToProduction']();
}

export function RegisterNewResolution() {
  return window['go']['services']['DIANService']['RegisterNewResolution']();
}

export function ResendInvoiceEmail(arg1, arg2) {
  return window['go']['services']['DIANService']['ResendInvoiceEmail'](arg1, arg2);
}

export function ResetConfigurationSteps() {
  return window['go']['services']['DIANService']['ResetConfigurationSteps']();
}

export function ResetTestResolution() {
  return window['go']['services']['DIANService']['ResetTestResolution']();
}

export function SendInvoice(arg1) {
  return window['go']['services']['DIANService']['SendInvoice'](arg1);
}

export function TestConnection() {
  return window['go']['services']['DIANService']['TestConnection']();
}

export function UpdateAlertThreshold(arg1) {
  return window['go']['services']['DIANService']['UpdateAlertThreshold'](arg1);
}

export function UpdateDIANConfig(arg1) {
  return window['go']['services']['DIANService']['UpdateDIANConfig'](arg1);
}
