// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeEnvironment(arg1) {
  return window['go']['services']['DIANService']['ChangeEnvironment'](arg1);
}

export function ConfigureCertificate() {
  return window['go']['services']['DIANService']['ConfigureCertificate']();
}

export function ConfigureCompany(arg1) {
  return window['go']['services']['DIANService']['ConfigureCompany'](arg1);
}

export function ConfigureResolution() {
  return window['go']['services']['DIANService']['ConfigureResolution']();
}

export function ConfigureSoftware() {
  return window['go']['services']['DIANService']['ConfigureSoftware']();
}

export function GetDIANConfig() {
  return window['go']['services']['DIANService']['GetDIANConfig']();
}

export function GetNumberingRanges() {
  return window['go']['services']['DIANService']['GetNumberingRanges']();
}

export function TestConnection() {
  return window['go']['services']['DIANService']['TestConnection']();
}

export function UpdateDIANConfig(arg1) {
  return window['go']['services']['DIANService']['UpdateDIANConfig'](arg1);
}
