// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCashMovement(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['EmployeeService']['AddCashMovement'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AuthenticateEmployee(arg1, arg2) {
  return window['go']['services']['EmployeeService']['AuthenticateEmployee'](arg1, arg2);
}

export function AuthenticateEmployeeByPIN(arg1) {
  return window['go']['services']['EmployeeService']['AuthenticateEmployeeByPIN'](arg1);
}

export function CleanExpiredSessions() {
  return window['go']['services']['EmployeeService']['CleanExpiredSessions']();
}

export function CloseCashRegister(arg1, arg2, arg3) {
  return window['go']['services']['EmployeeService']['CloseCashRegister'](arg1, arg2, arg3);
}

export function Create(arg1) {
  return window['go']['services']['EmployeeService']['Create'](arg1);
}

export function CreateEmployee(arg1, arg2, arg3) {
  return window['go']['services']['EmployeeService']['CreateEmployee'](arg1, arg2, arg3);
}

export function CreateSession(arg1, arg2, arg3) {
  return window['go']['services']['EmployeeService']['CreateSession'](arg1, arg2, arg3);
}

export function DeactivateEmployee(arg1) {
  return window['go']['services']['EmployeeService']['DeactivateEmployee'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['EmployeeService']['Delete'](arg1, arg2);
}

export function DeleteEmployee(arg1) {
  return window['go']['services']['EmployeeService']['DeleteEmployee'](arg1);
}

export function EnsureDB() {
  return window['go']['services']['EmployeeService']['EnsureDB']();
}

export function Find(arg1, arg2) {
  return window['go']['services']['EmployeeService']['Find'](arg1, arg2);
}

export function First(arg1, arg2) {
  return window['go']['services']['EmployeeService']['First'](arg1, arg2);
}

export function GetAuditLogs(arg1, arg2, arg3, arg4) {
  return window['go']['services']['EmployeeService']['GetAuditLogs'](arg1, arg2, arg3, arg4);
}

export function GetCashMovements(arg1) {
  return window['go']['services']['EmployeeService']['GetCashMovements'](arg1);
}

export function GetCashRegisterHistory(arg1, arg2) {
  return window['go']['services']['EmployeeService']['GetCashRegisterHistory'](arg1, arg2);
}

export function GetCashRegisterReport(arg1) {
  return window['go']['services']['EmployeeService']['GetCashRegisterReport'](arg1);
}

export function GetCashRegisterSalesSummary(arg1, arg2) {
  return window['go']['services']['EmployeeService']['GetCashRegisterSalesSummary'](arg1, arg2);
}

export function GetCurrentCashRegister() {
  return window['go']['services']['EmployeeService']['GetCurrentCashRegister']();
}

export function GetDB() {
  return window['go']['services']['EmployeeService']['GetDB']();
}

export function GetDailyCashRegisterReport(arg1) {
  return window['go']['services']['EmployeeService']['GetDailyCashRegisterReport'](arg1);
}

export function GetEmployee(arg1) {
  return window['go']['services']['EmployeeService']['GetEmployee'](arg1);
}

export function GetEmployees() {
  return window['go']['services']['EmployeeService']['GetEmployees']();
}

export function GetOpenCashRegister(arg1) {
  return window['go']['services']['EmployeeService']['GetOpenCashRegister'](arg1);
}

export function LogAudit(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['services']['EmployeeService']['LogAudit'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function Model(arg1) {
  return window['go']['services']['EmployeeService']['Model'](arg1);
}

export function OpenCashRegister(arg1, arg2, arg3) {
  return window['go']['services']['EmployeeService']['OpenCashRegister'](arg1, arg2, arg3);
}

export function Preload(arg1) {
  return window['go']['services']['EmployeeService']['Preload'](arg1);
}

export function PrintCurrentCashRegisterReport(arg1) {
  return window['go']['services']['EmployeeService']['PrintCurrentCashRegisterReport'](arg1);
}

export function PrintLastCashRegisterReport(arg1) {
  return window['go']['services']['EmployeeService']['PrintLastCashRegisterReport'](arg1);
}

export function RevokeSession(arg1) {
  return window['go']['services']['EmployeeService']['RevokeSession'](arg1);
}

export function Save(arg1) {
  return window['go']['services']['EmployeeService']['Save'](arg1);
}

export function SetDB(arg1) {
  return window['go']['services']['EmployeeService']['SetDB'](arg1);
}

export function UpdateCashMovement(arg1, arg2, arg3, arg4) {
  return window['go']['services']['EmployeeService']['UpdateCashMovement'](arg1, arg2, arg3, arg4);
}

export function UpdateEmployee(arg1) {
  return window['go']['services']['EmployeeService']['UpdateEmployee'](arg1);
}

export function UpdateEmployeePIN(arg1, arg2) {
  return window['go']['services']['EmployeeService']['UpdateEmployeePIN'](arg1, arg2);
}

export function UpdateEmployeePassword(arg1, arg2) {
  return window['go']['services']['EmployeeService']['UpdateEmployeePassword'](arg1, arg2);
}

export function ValidateSession(arg1) {
  return window['go']['services']['EmployeeService']['ValidateSession'](arg1);
}

export function Where(arg1, arg2) {
  return window['go']['services']['EmployeeService']['Where'](arg1, arg2);
}

export function WithTransaction(arg1) {
  return window['go']['services']['EmployeeService']['WithTransaction'](arg1);
}
