// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {gorm} from '../models';
import {time} from '../models';

export function AddCashMovement(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function AuthenticateEmployee(arg1:string,arg2:string):Promise<models.Employee>;

export function AuthenticateEmployeeByPIN(arg1:string):Promise<models.Employee>;

export function CleanExpiredSessions():Promise<void>;

export function CloseCashRegister(arg1:number,arg2:number,arg3:string):Promise<models.CashRegisterReport>;

export function Create(arg1:any):Promise<void>;

export function CreateEmployee(arg1:models.Employee,arg2:string,arg3:string):Promise<void>;

export function CreateSession(arg1:number,arg2:string,arg3:string):Promise<models.Session>;

export function DeactivateEmployee(arg1:number):Promise<void>;

export function Delete(arg1:any,arg2:number):Promise<void>;

export function DeleteEmployee(arg1:number):Promise<void>;

export function EnsureDB():Promise<void>;

export function Find(arg1:any,arg2:Array<any>):Promise<void>;

export function First(arg1:any,arg2:Array<any>):Promise<void>;

export function GetAuditLogs(arg1:number,arg2:string,arg3:number,arg4:number):Promise<Array<models.AuditLog>>;

export function GetCashMovements(arg1:number):Promise<Array<models.CashMovement>>;

export function GetCashRegisterHistory(arg1:number,arg2:number):Promise<Array<models.CashRegister>>;

export function GetCashRegisterReport(arg1:number):Promise<models.CashRegisterReport>;

export function GetCashRegisterSalesSummary(arg1:number,arg2:boolean):Promise<services.CashRegisterSalesSummary>;

export function GetCurrentCashRegister():Promise<models.CashRegister>;

export function GetDB():Promise<gorm.DB>;

export function GetDailyCashRegisterReport(arg1:time.Time):Promise<models.CashRegisterReport>;

export function GetEmployee(arg1:number):Promise<models.Employee>;

export function GetEmployees():Promise<Array<models.Employee>>;

export function GetOpenCashRegister(arg1:number):Promise<models.CashRegister>;

export function LogAudit(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function Model(arg1:any):Promise<gorm.DB>;

export function OpenCashRegister(arg1:number,arg2:number,arg3:string):Promise<models.CashRegister>;

export function Preload(arg1:string):Promise<gorm.DB>;

export function PrintCurrentCashRegisterReport(arg1:number):Promise<void>;

export function PrintLastCashRegisterReport(arg1:number):Promise<void>;

export function RevokeSession(arg1:string):Promise<void>;

export function Save(arg1:any):Promise<void>;

export function SetDB(arg1:gorm.DB):Promise<void>;

export function UpdateEmployee(arg1:models.Employee):Promise<void>;

export function UpdateEmployeePIN(arg1:number,arg2:string):Promise<void>;

export function UpdateEmployeePassword(arg1:number,arg2:string):Promise<void>;

export function ValidateSession(arg1:string):Promise<models.Employee>;

export function Where(arg1:any,arg2:Array<any>):Promise<gorm.DB>;

export function WithTransaction(arg1:any):Promise<void>;
