// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDailyReport(arg1) {
  return window['go']['services']['GoogleSheetsService']['GenerateDailyReport'](arg1);
}

export function GetConfig() {
  return window['go']['services']['GoogleSheetsService']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['services']['GoogleSheetsService']['SaveConfig'](arg1);
}

export function SendReport(arg1, arg2) {
  return window['go']['services']['GoogleSheetsService']['SendReport'](arg1, arg2);
}

export function SyncAllDays() {
  return window['go']['services']['GoogleSheetsService']['SyncAllDays']();
}

export function SyncNow() {
  return window['go']['services']['GoogleSheetsService']['SyncNow']();
}

export function TestConnection(arg1) {
  return window['go']['services']['GoogleSheetsService']['TestConnection'](arg1);
}
