// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {services} from '../models';
import {models} from '../models';

export function GenerateDailyReport(arg1:time.Time):Promise<services.ReportData>;

export function GetConfig():Promise<models.GoogleSheetsConfig>;

export function SaveConfig(arg1:models.GoogleSheetsConfig):Promise<void>;

export function SendReport(arg1:models.GoogleSheetsConfig,arg2:services.ReportData):Promise<void>;

export function SyncNow():Promise<void>;

export function TestConnection(arg1:models.GoogleSheetsConfig):Promise<void>;
