// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {gorm} from '../models';

export function AddProductIngredient(arg1:models.ProductIngredient):Promise<void>;

export function AdjustIngredientStock(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function CreateIngredient(arg1:models.Ingredient):Promise<void>;

export function DeductIngredientsForOrder(arg1:Array<models.OrderItem>):Promise<Array<string>>;

export function DeductIngredientsInTransaction(arg1:gorm.DB,arg2:Array<models.OrderItem>):Promise<Array<string>>;

export function DeleteIngredient(arg1:number):Promise<void>;

export function DeleteProductIngredient(arg1:number):Promise<void>;

export function GetAllIngredients():Promise<Array<models.Ingredient>>;

export function GetIngredient(arg1:number):Promise<models.Ingredient>;

export function GetIngredientMovements(arg1:number):Promise<Array<models.IngredientMovement>>;

export function GetLowStockIngredients():Promise<Array<models.Ingredient>>;

export function GetProductIngredients(arg1:number):Promise<Array<models.ProductIngredient>>;

export function RestoreIngredientsForOrder(arg1:Array<models.OrderItem>):Promise<void>;

export function SetProductIngredients(arg1:number,arg2:Array<models.ProductIngredient>):Promise<void>;

export function UpdateIngredient(arg1:models.Ingredient):Promise<void>;

export function UpdateProductIngredient(arg1:models.ProductIngredient):Promise<void>;
