// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProductIngredient(arg1) {
  return window['go']['services']['IngredientService']['AddProductIngredient'](arg1);
}

export function AdjustIngredientStock(arg1, arg2, arg3, arg4) {
  return window['go']['services']['IngredientService']['AdjustIngredientStock'](arg1, arg2, arg3, arg4);
}

export function CreateIngredient(arg1) {
  return window['go']['services']['IngredientService']['CreateIngredient'](arg1);
}

export function DeductIngredientsForOrder(arg1) {
  return window['go']['services']['IngredientService']['DeductIngredientsForOrder'](arg1);
}

export function DeductIngredientsInTransaction(arg1, arg2) {
  return window['go']['services']['IngredientService']['DeductIngredientsInTransaction'](arg1, arg2);
}

export function DeleteIngredient(arg1) {
  return window['go']['services']['IngredientService']['DeleteIngredient'](arg1);
}

export function DeleteProductIngredient(arg1) {
  return window['go']['services']['IngredientService']['DeleteProductIngredient'](arg1);
}

export function GetAllIngredients() {
  return window['go']['services']['IngredientService']['GetAllIngredients']();
}

export function GetIngredient(arg1) {
  return window['go']['services']['IngredientService']['GetIngredient'](arg1);
}

export function GetIngredientMovements(arg1) {
  return window['go']['services']['IngredientService']['GetIngredientMovements'](arg1);
}

export function GetLowStockIngredients() {
  return window['go']['services']['IngredientService']['GetLowStockIngredients']();
}

export function GetProductIngredients(arg1) {
  return window['go']['services']['IngredientService']['GetProductIngredients'](arg1);
}

export function RestoreIngredientsForOrder(arg1) {
  return window['go']['services']['IngredientService']['RestoreIngredientsForOrder'](arg1);
}

export function SetProductIngredients(arg1, arg2) {
  return window['go']['services']['IngredientService']['SetProductIngredients'](arg1, arg2);
}

export function UpdateIngredient(arg1) {
  return window['go']['services']['IngredientService']['UpdateIngredient'](arg1);
}

export function UpdateProductIngredient(arg1) {
  return window['go']['services']['IngredientService']['UpdateProductIngredient'](arg1);
}
