// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetConfig():Promise<services.InvoiceLimitConfig>;

export function GetStatus():Promise<services.InvoiceLimitStatus>;

export function IncrementAlternatingCounter():Promise<void>;

export function SaveConfig(arg1:services.InvoiceLimitConfig):Promise<void>;

export function StartPeriodicSync():Promise<void>;

export function StopPeriodicSync():Promise<void>;

export function SyncConfig():Promise<void>;
