// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['services']['InvoiceLimitService']['GetConfig']();
}

export function GetStatus() {
  return window['go']['services']['InvoiceLimitService']['GetStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['services']['InvoiceLimitService']['SaveConfig'](arg1);
}

export function StartPeriodicSync() {
  return window['go']['services']['InvoiceLimitService']['StartPeriodicSync']();
}

export function StopPeriodicSync() {
  return window['go']['services']['InvoiceLimitService']['StopPeriodicSync']();
}

export function SyncConfig() {
  return window['go']['services']['InvoiceLimitService']['SyncConfig']();
}
