// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanOldLogs(arg1) {
  return window['go']['services']['LoggerService']['CleanOldLogs'](arg1);
}

export function Close() {
  return window['go']['services']['LoggerService']['Close']();
}

export function GetLogDirectory() {
  return window['go']['services']['LoggerService']['GetLogDirectory']();
}

export function GetTodayLogPath() {
  return window['go']['services']['LoggerService']['GetTodayLogPath']();
}

export function LogError(arg1, arg2, arg3) {
  return window['go']['services']['LoggerService']['LogError'](arg1, arg2, arg3);
}

export function LogFatal(arg1, arg2) {
  return window['go']['services']['LoggerService']['LogFatal'](arg1, arg2);
}

export function LogFrontendError(arg1, arg2, arg3) {
  return window['go']['services']['LoggerService']['LogFrontendError'](arg1, arg2, arg3);
}

export function LogFrontendInfo(arg1, arg2) {
  return window['go']['services']['LoggerService']['LogFrontendInfo'](arg1, arg2);
}

export function LogFrontendWarning(arg1, arg2) {
  return window['go']['services']['LoggerService']['LogFrontendWarning'](arg1, arg2);
}

export function LogInfo(arg1, arg2) {
  return window['go']['services']['LoggerService']['LogInfo'](arg1, arg2);
}

export function LogPanic(arg1) {
  return window['go']['services']['LoggerService']['LogPanic'](arg1);
}

export function LogWarning(arg1, arg2) {
  return window['go']['services']['LoggerService']['LogWarning'](arg1, arg2);
}

export function RecoverPanic() {
  return window['go']['services']['LoggerService']['RecoverPanic']();
}
