// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanOldLogs(arg1:number):Promise<void>;

export function Close():Promise<void>;

export function GetLogDirectory():Promise<string>;

export function GetTodayLogPath():Promise<string>;

export function LogError(arg1:string,arg2:Error,arg3:Array<string>):Promise<void>;

export function LogFatal(arg1:string,arg2:Error):Promise<void>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogFrontendInfo(arg1:string,arg2:string):Promise<void>;

export function LogFrontendWarning(arg1:string,arg2:string):Promise<void>;

export function LogInfo(arg1:string,arg2:Array<string>):Promise<void>;

export function LogPanic(arg1:any):Promise<void>;

export function LogWarning(arg1:string,arg2:Array<string>):Promise<void>;

export function RecoverPanic():Promise<void>;
