// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AutoStart():Promise<void>;

export function GetAvailableTools():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<models.MCPConfig>;

export function GetEnabledTools():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function Start():Promise<void>;

export function Stop():Promise<void>;

export function UpdateConfig(arg1:models.MCPConfig):Promise<void>;
