// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoStart() {
  return window['go']['services']['MCPService']['AutoStart']();
}

export function GetAvailableTools() {
  return window['go']['services']['MCPService']['GetAvailableTools']();
}

export function GetConfig() {
  return window['go']['services']['MCPService']['GetConfig']();
}

export function GetEnabledTools() {
  return window['go']['services']['MCPService']['GetEnabledTools']();
}

export function GetStatus() {
  return window['go']['services']['MCPService']['GetStatus']();
}

export function Start() {
  return window['go']['services']['MCPService']['Start']();
}

export function Stop() {
  return window['go']['services']['MCPService']['Stop']();
}

export function UpdateConfig(arg1) {
  return window['go']['services']['MCPService']['UpdateConfig'](arg1);
}
