// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateOrderType(arg1:models.OrderType):Promise<void>;

export function DeleteOrderType(arg1:number):Promise<void>;

export function GetActiveOrderTypes():Promise<Array<models.OrderType>>;

export function GetAllOrderTypes():Promise<Array<models.OrderType>>;

export function GetNextSequenceNumber(arg1:number):Promise<number>;

export function GetOrderType(arg1:number):Promise<models.OrderType>;

export function GetOrderTypeByCode(arg1:string):Promise<models.OrderType>;

export function ReorderOrderTypes(arg1:Array<number>):Promise<void>;

export function UpdateOrderType(arg1:models.OrderType):Promise<void>;
