// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemToOrder(arg1, arg2) {
  return window['go']['services']['OrderService']['AddItemToOrder'](arg1, arg2);
}

export function AssignOrderToTable(arg1, arg2) {
  return window['go']['services']['OrderService']['AssignOrderToTable'](arg1, arg2);
}

export function CancelOrder(arg1, arg2) {
  return window['go']['services']['OrderService']['CancelOrder'](arg1, arg2);
}

export function CreateOrder(arg1) {
  return window['go']['services']['OrderService']['CreateOrder'](arg1);
}

export function CreateTable(arg1) {
  return window['go']['services']['OrderService']['CreateTable'](arg1);
}

export function CreateTableArea(arg1) {
  return window['go']['services']['OrderService']['CreateTableArea'](arg1);
}

export function DeleteTable(arg1) {
  return window['go']['services']['OrderService']['DeleteTable'](arg1);
}

export function DeleteTableArea(arg1) {
  return window['go']['services']['OrderService']['DeleteTableArea'](arg1);
}

export function GetOrder(arg1) {
  return window['go']['services']['OrderService']['GetOrder'](arg1);
}

export function GetOrderByNumber(arg1) {
  return window['go']['services']['OrderService']['GetOrderByNumber'](arg1);
}

export function GetOrdersByDateRange(arg1, arg2) {
  return window['go']['services']['OrderService']['GetOrdersByDateRange'](arg1, arg2);
}

export function GetOrdersByStatus(arg1) {
  return window['go']['services']['OrderService']['GetOrdersByStatus'](arg1);
}

export function GetOrdersByTable(arg1) {
  return window['go']['services']['OrderService']['GetOrdersByTable'](arg1);
}

export function GetPendingOrders() {
  return window['go']['services']['OrderService']['GetPendingOrders']();
}

export function GetTable(arg1) {
  return window['go']['services']['OrderService']['GetTable'](arg1);
}

export function GetTableAreas() {
  return window['go']['services']['OrderService']['GetTableAreas']();
}

export function GetTables() {
  return window['go']['services']['OrderService']['GetTables']();
}

export function GetTodayOrders() {
  return window['go']['services']['OrderService']['GetTodayOrders']();
}

export function RemoveItemFromOrder(arg1, arg2) {
  return window['go']['services']['OrderService']['RemoveItemFromOrder'](arg1, arg2);
}

export function UpdateOrder(arg1) {
  return window['go']['services']['OrderService']['UpdateOrder'](arg1);
}

export function UpdateOrderStatus(arg1, arg2) {
  return window['go']['services']['OrderService']['UpdateOrderStatus'](arg1, arg2);
}

export function UpdateTable(arg1) {
  return window['go']['services']['OrderService']['UpdateTable'](arg1);
}

export function UpdateTableArea(arg1) {
  return window['go']['services']['OrderService']['UpdateTableArea'](arg1);
}

export function UpdateTableStatus(arg1, arg2) {
  return window['go']['services']['OrderService']['UpdateTableStatus'](arg1, arg2);
}
