// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrderType(arg1) {
  return window['go']['services']['OrderTypeService']['CreateOrderType'](arg1);
}

export function DeleteOrderType(arg1) {
  return window['go']['services']['OrderTypeService']['DeleteOrderType'](arg1);
}

export function GetActiveOrderTypes() {
  return window['go']['services']['OrderTypeService']['GetActiveOrderTypes']();
}

export function GetAllOrderTypes() {
  return window['go']['services']['OrderTypeService']['GetAllOrderTypes']();
}

export function GetNextSequenceNumber(arg1) {
  return window['go']['services']['OrderTypeService']['GetNextSequenceNumber'](arg1);
}

export function GetOrderType(arg1) {
  return window['go']['services']['OrderTypeService']['GetOrderType'](arg1);
}

export function GetOrderTypeByCode(arg1) {
  return window['go']['services']['OrderTypeService']['GetOrderTypeByCode'](arg1);
}

export function ReorderOrderTypes(arg1) {
  return window['go']['services']['OrderTypeService']['ReorderOrderTypes'](arg1);
}

export function UpdateOrderType(arg1) {
  return window['go']['services']['OrderTypeService']['UpdateOrderType'](arg1);
}
