// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';
import {websocket} from '../models';

export function AddItemToOrder(arg1:number,arg2:models.OrderItem):Promise<void>;

export function AssignOrderToTable(arg1:number,arg2:number):Promise<void>;

export function CancelOrder(arg1:number,arg2:string):Promise<void>;

export function CreateOrder(arg1:models.Order):Promise<models.Order>;

export function CreateTable(arg1:models.Table):Promise<void>;

export function CreateTableArea(arg1:models.TableArea):Promise<void>;

export function DeleteOrder(arg1:number):Promise<void>;

export function DeleteTable(arg1:number):Promise<void>;

export function DeleteTableArea(arg1:number):Promise<void>;

export function GetOrder(arg1:number):Promise<models.Order>;

export function GetOrderByNumber(arg1:string):Promise<models.Order>;

export function GetOrdersByDateRange(arg1:time.Time,arg2:time.Time):Promise<Array<models.Order>>;

export function GetOrdersByStatus(arg1:models.OrderStatus):Promise<Array<models.Order>>;

export function GetOrdersByTable(arg1:number):Promise<Array<models.Order>>;

export function GetPendingOrders():Promise<Array<models.Order>>;

export function GetTable(arg1:number):Promise<models.Table>;

export function GetTableAreas():Promise<Array<models.TableArea>>;

export function GetTables():Promise<Array<models.Table>>;

export function GetTodayOrders():Promise<Array<models.Order>>;

export function RemoveItemFromOrder(arg1:number,arg2:number):Promise<void>;

export function SendToKitchen(arg1:number):Promise<void>;

export function SetWebSocketServer(arg1:websocket.Server):Promise<void>;

export function UpdateOrder(arg1:models.Order):Promise<void>;

export function UpdateOrderStatus(arg1:number,arg2:models.OrderStatus):Promise<void>;

export function UpdateTable(arg1:models.Table):Promise<void>;

export function UpdateTableArea(arg1:models.TableArea):Promise<void>;

export function UpdateTableStatus(arg1:number,arg2:string):Promise<void>;
