// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetDepartments():Promise<Array<models.Department>>;

export function GetMunicipalities():Promise<Array<models.Municipality>>;

export function GetMunicipalitiesByDepartment(arg1:number):Promise<Array<models.Municipality>>;

export function GetPaymentMethods():Promise<Array<models.DIANPaymentMethod>>;

export function GetTypeDocumentIdentifications():Promise<Array<models.TypeDocumentIdentification>>;

export function GetTypeLiabilities():Promise<Array<models.TypeLiability>>;

export function GetTypeOrganizations():Promise<Array<models.TypeOrganization>>;

export function GetTypeRegimes():Promise<Array<models.TypeRegime>>;
