// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDepartments() {
  return window['go']['services']['ParametricService']['GetDepartments']();
}

export function GetMunicipalities() {
  return window['go']['services']['ParametricService']['GetMunicipalities']();
}

export function GetMunicipalitiesByDepartment(arg1) {
  return window['go']['services']['ParametricService']['GetMunicipalitiesByDepartment'](arg1);
}

export function GetPaymentMethods() {
  return window['go']['services']['ParametricService']['GetPaymentMethods']();
}

export function GetTypeDocumentIdentifications() {
  return window['go']['services']['ParametricService']['GetTypeDocumentIdentifications']();
}

export function GetTypeLiabilities() {
  return window['go']['services']['ParametricService']['GetTypeLiabilities']();
}

export function GetTypeOrganizations() {
  return window['go']['services']['ParametricService']['GetTypeOrganizations']();
}

export function GetTypeRegimes() {
  return window['go']['services']['ParametricService']['GetTypeRegimes']();
}
