// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {models} from '../models';

export function GetAvailablePrinters():Promise<Array<services.DetectedPrinter>>;

export function GetAvailableSerialPorts():Promise<Array<string>>;

export function PrintCashRegisterReport(arg1:models.CashRegisterReport):Promise<void>;

export function PrintKitchenOrder(arg1:models.Order):Promise<void>;

export function PrintReceipt(arg1:models.Sale,arg2:boolean):Promise<void>;

export function PrintReceiptWithPrinter(arg1:models.Sale,arg2:boolean,arg3:number):Promise<void>;

export function TestPrinter(arg1:number):Promise<void>;
