// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailablePrinters() {
  return window['go']['services']['PrinterService']['GetAvailablePrinters']();
}

export function GetAvailableSerialPorts() {
  return window['go']['services']['PrinterService']['GetAvailableSerialPorts']();
}

export function PrintCashRegisterReport(arg1) {
  return window['go']['services']['PrinterService']['PrintCashRegisterReport'](arg1);
}

export function PrintCustomerDataForm() {
  return window['go']['services']['PrinterService']['PrintCustomerDataForm']();
}

export function PrintDIANClosingReport(arg1) {
  return window['go']['services']['PrinterService']['PrintDIANClosingReport'](arg1);
}

export function PrintKitchenOrder(arg1) {
  return window['go']['services']['PrinterService']['PrintKitchenOrder'](arg1);
}

export function PrintOrder(arg1) {
  return window['go']['services']['PrinterService']['PrintOrder'](arg1);
}

export function PrintReceipt(arg1, arg2) {
  return window['go']['services']['PrinterService']['PrintReceipt'](arg1, arg2);
}

export function PrintReceiptWithPrinter(arg1, arg2, arg3) {
  return window['go']['services']['PrinterService']['PrintReceiptWithPrinter'](arg1, arg2, arg3);
}

export function TestPrinter(arg1) {
  return window['go']['services']['PrinterService']['TestPrinter'](arg1);
}
