// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {models} from '../models';
import {services} from '../models';

export function AdjustStock(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function AdjustStockInTransaction(arg1:gorm.DB,arg2:number,arg3:number,arg4:string,arg5:number):Promise<void>;

export function AssignModifierToProduct(arg1:number,arg2:number):Promise<void>;

export function Create(arg1:any):Promise<void>;

export function CreateCategory(arg1:models.Category):Promise<models.Category>;

export function CreateModifier(arg1:models.Modifier):Promise<void>;

export function CreateModifierGroup(arg1:models.ModifierGroup):Promise<void>;

export function CreateProduct(arg1:models.Product):Promise<models.Product>;

export function Delete(arg1:any,arg2:number):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteModifier(arg1:number):Promise<void>;

export function DeleteModifierGroup(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function EnsureDB():Promise<void>;

export function ExportProducts(arg1:string):Promise<Array<number>>;

export function Find(arg1:any,arg2:Array<any>):Promise<void>;

export function First(arg1:any,arg2:Array<any>):Promise<void>;

export function GetAllCategories():Promise<Array<models.Category>>;

export function GetAllProducts():Promise<Array<models.Product>>;

export function GetDB():Promise<gorm.DB>;

export function GetInventoryMovements(arg1:number):Promise<Array<models.InventoryMovement>>;

export function GetInventorySummary():Promise<services.InventorySummary>;

export function GetLowStockProducts(arg1:number):Promise<Array<models.Product>>;

export function GetModifierGroups():Promise<Array<models.ModifierGroup>>;

export function GetModifiers():Promise<Array<models.Modifier>>;

export function GetProduct(arg1:number):Promise<models.Product>;

export function GetProductsByCategory(arg1:number):Promise<Array<models.Product>>;

export function ImportProducts(arg1:Array<number>,arg2:string):Promise<void>;

export function Model(arg1:any):Promise<gorm.DB>;

export function Preload(arg1:string):Promise<gorm.DB>;

export function RemoveModifierFromProduct(arg1:number,arg2:number):Promise<void>;

export function Save(arg1:any):Promise<void>;

export function SearchProducts(arg1:string):Promise<Array<models.Product>>;

export function SetDB(arg1:gorm.DB):Promise<void>;

export function UpdateCategory(arg1:models.Category):Promise<models.Category>;

export function UpdateModifier(arg1:models.Modifier):Promise<void>;

export function UpdateModifierGroup(arg1:models.ModifierGroup):Promise<void>;

export function UpdateProduct(arg1:models.Product):Promise<void>;

export function Where(arg1:any,arg2:Array<any>):Promise<gorm.DB>;

export function WithTransaction(arg1:any):Promise<void>;
