// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustStock(arg1, arg2, arg3, arg4) {
  return window['go']['services']['ProductService']['AdjustStock'](arg1, arg2, arg3, arg4);
}

export function AdjustStockInTransaction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['ProductService']['AdjustStockInTransaction'](arg1, arg2, arg3, arg4, arg5);
}

export function AssignModifierToProduct(arg1, arg2) {
  return window['go']['services']['ProductService']['AssignModifierToProduct'](arg1, arg2);
}

export function Create(arg1) {
  return window['go']['services']['ProductService']['Create'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['services']['ProductService']['CreateCategory'](arg1);
}

export function CreateModifier(arg1) {
  return window['go']['services']['ProductService']['CreateModifier'](arg1);
}

export function CreateModifierGroup(arg1) {
  return window['go']['services']['ProductService']['CreateModifierGroup'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['services']['ProductService']['CreateProduct'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['ProductService']['Delete'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['services']['ProductService']['DeleteCategory'](arg1);
}

export function DeleteModifier(arg1) {
  return window['go']['services']['ProductService']['DeleteModifier'](arg1);
}

export function DeleteModifierGroup(arg1) {
  return window['go']['services']['ProductService']['DeleteModifierGroup'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['services']['ProductService']['DeleteProduct'](arg1);
}

export function EnsureDB() {
  return window['go']['services']['ProductService']['EnsureDB']();
}

export function ExportProducts(arg1) {
  return window['go']['services']['ProductService']['ExportProducts'](arg1);
}

export function Find(arg1, arg2) {
  return window['go']['services']['ProductService']['Find'](arg1, arg2);
}

export function First(arg1, arg2) {
  return window['go']['services']['ProductService']['First'](arg1, arg2);
}

export function GetAllCategories() {
  return window['go']['services']['ProductService']['GetAllCategories']();
}

export function GetAllProducts() {
  return window['go']['services']['ProductService']['GetAllProducts']();
}

export function GetDB() {
  return window['go']['services']['ProductService']['GetDB']();
}

export function GetInventoryMovements(arg1) {
  return window['go']['services']['ProductService']['GetInventoryMovements'](arg1);
}

export function GetInventorySummary() {
  return window['go']['services']['ProductService']['GetInventorySummary']();
}

export function GetLowStockProducts(arg1) {
  return window['go']['services']['ProductService']['GetLowStockProducts'](arg1);
}

export function GetModifierGroups() {
  return window['go']['services']['ProductService']['GetModifierGroups']();
}

export function GetModifiers() {
  return window['go']['services']['ProductService']['GetModifiers']();
}

export function GetProduct(arg1) {
  return window['go']['services']['ProductService']['GetProduct'](arg1);
}

export function GetProductsByCategory(arg1) {
  return window['go']['services']['ProductService']['GetProductsByCategory'](arg1);
}

export function ImportProducts(arg1, arg2) {
  return window['go']['services']['ProductService']['ImportProducts'](arg1, arg2);
}

export function Model(arg1) {
  return window['go']['services']['ProductService']['Model'](arg1);
}

export function Preload(arg1) {
  return window['go']['services']['ProductService']['Preload'](arg1);
}

export function RemoveModifierFromProduct(arg1, arg2) {
  return window['go']['services']['ProductService']['RemoveModifierFromProduct'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['services']['ProductService']['Save'](arg1);
}

export function SearchProducts(arg1) {
  return window['go']['services']['ProductService']['SearchProducts'](arg1);
}

export function SetDB(arg1) {
  return window['go']['services']['ProductService']['SetDB'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['services']['ProductService']['UpdateCategory'](arg1);
}

export function UpdateModifier(arg1) {
  return window['go']['services']['ProductService']['UpdateModifier'](arg1);
}

export function UpdateModifierGroup(arg1) {
  return window['go']['services']['ProductService']['UpdateModifierGroup'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['services']['ProductService']['UpdateProduct'](arg1);
}

export function Where(arg1, arg2) {
  return window['go']['services']['ProductService']['Where'](arg1, arg2);
}

export function WithTransaction(arg1) {
  return window['go']['services']['ProductService']['WithTransaction'](arg1);
}
