// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['services']['RappiConfigService']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['services']['RappiConfigService']['GetConnectionStatus']();
}

export function GetStoreIDs() {
  return window['go']['services']['RappiConfigService']['GetStoreIDs']();
}

export function GetToken(arg1) {
  return window['go']['services']['RappiConfigService']['GetToken'](arg1);
}

export function MakeAuthenticatedRequest(arg1, arg2, arg3) {
  return window['go']['services']['RappiConfigService']['MakeAuthenticatedRequest'](arg1, arg2, arg3);
}

export function ResetStatistics() {
  return window['go']['services']['RappiConfigService']['ResetStatistics']();
}

export function SaveConfig(arg1) {
  return window['go']['services']['RappiConfigService']['SaveConfig'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['services']['RappiConfigService']['TestConnection'](arg1);
}

export function ValidateStoreIDs() {
  return window['go']['services']['RappiConfigService']['ValidateStoreIDs']();
}
