// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function GetConfig():Promise<models.RappiConfig>;

export function GetConnectionStatus():Promise<services.ConnectionStatus>;

export function GetStoreIDs():Promise<Array<string>>;

export function GetToken(arg1:boolean):Promise<string>;

export function MakeAuthenticatedRequest(arg1:string,arg2:string,arg3:any):Promise<Array<number>>;

export function ResetStatistics():Promise<void>;

export function SaveConfig(arg1:models.RappiConfig):Promise<void>;

export function TestConnection(arg1:models.RappiConfig):Promise<services.TestConnectionResponse>;

export function ValidateStoreIDs():Promise<void>;
