// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportSalesReportCSV(arg1) {
  return window['go']['services']['ReportsService']['ExportSalesReportCSV'](arg1);
}

export function ExportSalesReportJSON(arg1) {
  return window['go']['services']['ReportsService']['ExportSalesReportJSON'](arg1);
}

export function GetCustomerStats(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetCustomerStats'](arg1, arg2);
}

export function GetDailySalesReport(arg1) {
  return window['go']['services']['ReportsService']['GetDailySalesReport'](arg1);
}

export function GetDashboardStats() {
  return window['go']['services']['ReportsService']['GetDashboardStats']();
}

export function GetEmployeePerformanceReport(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetEmployeePerformanceReport'](arg1, arg2);
}

export function GetEmployeeSalesReport(arg1, arg2, arg3) {
  return window['go']['services']['ReportsService']['GetEmployeeSalesReport'](arg1, arg2, arg3);
}

export function GetInventoryReport() {
  return window['go']['services']['ReportsService']['GetInventoryReport']();
}

export function GetKeyMetricsComparison(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetKeyMetricsComparison'](arg1, arg2);
}

export function GetLowStockReport(arg1) {
  return window['go']['services']['ReportsService']['GetLowStockReport'](arg1);
}

export function GetMonthlySalesReport(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetMonthlySalesReport'](arg1, arg2);
}

export function GetSalesByCategory(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetSalesByCategory'](arg1, arg2);
}

export function GetSalesByPaymentMethod(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetSalesByPaymentMethod'](arg1, arg2);
}

export function GetSalesReport(arg1, arg2) {
  return window['go']['services']['ReportsService']['GetSalesReport'](arg1, arg2);
}

export function GetWeeklySalesReport() {
  return window['go']['services']['ReportsService']['GetWeeklySalesReport']();
}
