// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['services']['ReportSchedulerService']['GetStatus']();
}

export function Restart() {
  return window['go']['services']['ReportSchedulerService']['Restart']();
}

export function Start() {
  return window['go']['services']['ReportSchedulerService']['Start']();
}

export function Stop() {
  return window['go']['services']['ReportSchedulerService']['Stop']();
}
