// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {gorm} from '../models';
import {time} from '../models';

export function ConvertToElectronicInvoice(arg1:number):Promise<void>;

export function Create(arg1:any):Promise<void>;

export function CreateCustomer(arg1:models.Customer):Promise<void>;

export function CreatePaymentMethod(arg1:models.PaymentMethod):Promise<void>;

export function CreateQuickSale(arg1:services.QuickSaleRequest):Promise<models.Sale>;

export function DeactivatePaymentMethod(arg1:number):Promise<void>;

export function Delete(arg1:any,arg2:number):Promise<void>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function DeletePaymentMethod(arg1:number):Promise<void>;

export function DeleteSale(arg1:number,arg2:number):Promise<void>;

export function EnsureDB():Promise<void>;

export function Find(arg1:any,arg2:Array<any>):Promise<void>;

export function First(arg1:any,arg2:Array<any>):Promise<void>;

export function GetAllPaymentMethods():Promise<Array<models.PaymentMethod>>;

export function GetConsumidorFinal():Promise<models.Customer>;

export function GetCustomer(arg1:number):Promise<models.Customer>;

export function GetCustomerStats(arg1:boolean):Promise<services.CustomerStats>;

export function GetCustomers():Promise<Array<models.Customer>>;

export function GetDB():Promise<gorm.DB>;

export function GetDIANClosingReport(arg1:string):Promise<services.DIANClosingReport>;

export function GetDIANClosingReportWithPeriod(arg1:string,arg2:string):Promise<services.DIANClosingReport>;

export function GetPaymentMethodSalesCount(arg1:number):Promise<number>;

export function GetPaymentMethods():Promise<Array<models.PaymentMethod>>;

export function GetSale(arg1:number):Promise<models.Sale>;

export function GetSaleByNumber(arg1:string):Promise<models.Sale>;

export function GetSalesByDateRange(arg1:time.Time,arg2:time.Time):Promise<Array<models.Sale>>;

export function GetSalesHistory(arg1:number,arg2:number):Promise<Record<string, any>>;

export function GetSalesReport(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetTodaySales():Promise<Array<models.Sale>>;

export function Model(arg1:any):Promise<gorm.DB>;

export function Preload(arg1:string):Promise<gorm.DB>;

export function PrintDIANClosingReport(arg1:string):Promise<void>;

export function PrintReceipt(arg1:number):Promise<void>;

export function PrintReceiptWithPrinter(arg1:number,arg2:number):Promise<void>;

export function ProcessSale(arg1:number,arg2:Array<services.PaymentData>,arg3:models.Customer,arg4:boolean,arg5:boolean,arg6:number,arg7:number,arg8:boolean):Promise<models.Sale>;

export function RefundSale(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function ResendElectronicInvoice(arg1:number):Promise<void>;

export function Save(arg1:any):Promise<void>;

export function SearchCustomers(arg1:string):Promise<Array<models.Customer>>;

export function SetDB(arg1:gorm.DB):Promise<void>;

export function UpdateCustomer(arg1:models.Customer):Promise<void>;

export function UpdatePaymentMethod(arg1:models.PaymentMethod):Promise<void>;

export function Where(arg1:any,arg2:Array<any>):Promise<gorm.DB>;

export function WithTransaction(arg1:any):Promise<void>;
