// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToElectronicInvoice(arg1) {
  return window['go']['services']['SalesService']['ConvertToElectronicInvoice'](arg1);
}

export function Create(arg1) {
  return window['go']['services']['SalesService']['Create'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['services']['SalesService']['CreateCustomer'](arg1);
}

export function CreatePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['CreatePaymentMethod'](arg1);
}

export function CreateQuickSale(arg1) {
  return window['go']['services']['SalesService']['CreateQuickSale'](arg1);
}

export function DeactivatePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['DeactivatePaymentMethod'](arg1);
}

export function Delete(arg1, arg2) {
  return window['go']['services']['SalesService']['Delete'](arg1, arg2);
}

export function DeleteCustomer(arg1) {
  return window['go']['services']['SalesService']['DeleteCustomer'](arg1);
}

export function DeletePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['DeletePaymentMethod'](arg1);
}

export function DeleteSale(arg1, arg2) {
  return window['go']['services']['SalesService']['DeleteSale'](arg1, arg2);
}

export function EnsureDB() {
  return window['go']['services']['SalesService']['EnsureDB']();
}

export function Find(arg1, arg2) {
  return window['go']['services']['SalesService']['Find'](arg1, arg2);
}

export function First(arg1, arg2) {
  return window['go']['services']['SalesService']['First'](arg1, arg2);
}

export function GetAllPaymentMethods() {
  return window['go']['services']['SalesService']['GetAllPaymentMethods']();
}

export function GetConsumidorFinal() {
  return window['go']['services']['SalesService']['GetConsumidorFinal']();
}

export function GetCustomer(arg1) {
  return window['go']['services']['SalesService']['GetCustomer'](arg1);
}

export function GetCustomerStats(arg1) {
  return window['go']['services']['SalesService']['GetCustomerStats'](arg1);
}

export function GetCustomers() {
  return window['go']['services']['SalesService']['GetCustomers']();
}

export function GetDB() {
  return window['go']['services']['SalesService']['GetDB']();
}

export function GetDIANClosingReport(arg1) {
  return window['go']['services']['SalesService']['GetDIANClosingReport'](arg1);
}

export function GetDIANClosingReportCustomRange(arg1, arg2) {
  return window['go']['services']['SalesService']['GetDIANClosingReportCustomRange'](arg1, arg2);
}

export function GetDIANClosingReportWithPeriod(arg1, arg2) {
  return window['go']['services']['SalesService']['GetDIANClosingReportWithPeriod'](arg1, arg2);
}

export function GetPaymentMethodSalesCount(arg1) {
  return window['go']['services']['SalesService']['GetPaymentMethodSalesCount'](arg1);
}

export function GetPaymentMethods() {
  return window['go']['services']['SalesService']['GetPaymentMethods']();
}

export function GetSale(arg1) {
  return window['go']['services']['SalesService']['GetSale'](arg1);
}

export function GetSaleByNumber(arg1) {
  return window['go']['services']['SalesService']['GetSaleByNumber'](arg1);
}

export function GetSalesByDateRange(arg1, arg2) {
  return window['go']['services']['SalesService']['GetSalesByDateRange'](arg1, arg2);
}

export function GetSalesHistory(arg1, arg2) {
  return window['go']['services']['SalesService']['GetSalesHistory'](arg1, arg2);
}

export function GetSalesReport(arg1, arg2) {
  return window['go']['services']['SalesService']['GetSalesReport'](arg1, arg2);
}

export function GetTodaySales() {
  return window['go']['services']['SalesService']['GetTodaySales']();
}

export function Model(arg1) {
  return window['go']['services']['SalesService']['Model'](arg1);
}

export function Preload(arg1) {
  return window['go']['services']['SalesService']['Preload'](arg1);
}

export function PrintDIANClosingReport(arg1) {
  return window['go']['services']['SalesService']['PrintDIANClosingReport'](arg1);
}

export function PrintDIANClosingReportCustomRange(arg1, arg2) {
  return window['go']['services']['SalesService']['PrintDIANClosingReportCustomRange'](arg1, arg2);
}

export function PrintDIANClosingReportWithPeriod(arg1, arg2) {
  return window['go']['services']['SalesService']['PrintDIANClosingReportWithPeriod'](arg1, arg2);
}

export function PrintReceipt(arg1) {
  return window['go']['services']['SalesService']['PrintReceipt'](arg1);
}

export function PrintReceiptWithPrinter(arg1, arg2) {
  return window['go']['services']['SalesService']['PrintReceiptWithPrinter'](arg1, arg2);
}

export function ProcessSale(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['services']['SalesService']['ProcessSale'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RefundSale(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SalesService']['RefundSale'](arg1, arg2, arg3, arg4);
}

export function ResendElectronicInvoice(arg1) {
  return window['go']['services']['SalesService']['ResendElectronicInvoice'](arg1);
}

export function Save(arg1) {
  return window['go']['services']['SalesService']['Save'](arg1);
}

export function SearchCustomers(arg1) {
  return window['go']['services']['SalesService']['SearchCustomers'](arg1);
}

export function SetDB(arg1) {
  return window['go']['services']['SalesService']['SetDB'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['services']['SalesService']['UpdateCustomer'](arg1);
}

export function UpdatePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['UpdatePaymentMethod'](arg1);
}

export function UpdateSaleCustomer(arg1, arg2) {
  return window['go']['services']['SalesService']['UpdateSaleCustomer'](arg1, arg2);
}

export function Where(arg1, arg2) {
  return window['go']['services']['SalesService']['Where'](arg1, arg2);
}

export function WithTransaction(arg1) {
  return window['go']['services']['SalesService']['WithTransaction'](arg1);
}
