// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1) {
  return window['go']['services']['SalesService']['CreateCustomer'](arg1);
}

export function CreatePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['CreatePaymentMethod'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['services']['SalesService']['DeleteCustomer'](arg1);
}

export function DeletePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['DeletePaymentMethod'](arg1);
}

export function GetCustomer(arg1) {
  return window['go']['services']['SalesService']['GetCustomer'](arg1);
}

export function GetCustomers() {
  return window['go']['services']['SalesService']['GetCustomers']();
}

export function GetPaymentMethods() {
  return window['go']['services']['SalesService']['GetPaymentMethods']();
}

export function GetSale(arg1) {
  return window['go']['services']['SalesService']['GetSale'](arg1);
}

export function GetSaleByNumber(arg1) {
  return window['go']['services']['SalesService']['GetSaleByNumber'](arg1);
}

export function GetSalesByDateRange(arg1, arg2) {
  return window['go']['services']['SalesService']['GetSalesByDateRange'](arg1, arg2);
}

export function GetSalesHistory(arg1, arg2) {
  return window['go']['services']['SalesService']['GetSalesHistory'](arg1, arg2);
}

export function GetSalesReport(arg1, arg2) {
  return window['go']['services']['SalesService']['GetSalesReport'](arg1, arg2);
}

export function GetTodaySales() {
  return window['go']['services']['SalesService']['GetTodaySales']();
}

export function PrintReceipt(arg1) {
  return window['go']['services']['SalesService']['PrintReceipt'](arg1);
}

export function PrintReceiptWithPrinter(arg1, arg2) {
  return window['go']['services']['SalesService']['PrintReceiptWithPrinter'](arg1, arg2);
}

export function ProcessSale(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['services']['SalesService']['ProcessSale'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function RefundSale(arg1, arg2, arg3, arg4) {
  return window['go']['services']['SalesService']['RefundSale'](arg1, arg2, arg3, arg4);
}

export function ResendElectronicInvoice(arg1) {
  return window['go']['services']['SalesService']['ResendElectronicInvoice'](arg1);
}

export function SearchCustomers(arg1) {
  return window['go']['services']['SalesService']['SearchCustomers'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['services']['SalesService']['UpdateCustomer'](arg1);
}

export function UpdatePaymentMethod(arg1) {
  return window['go']['services']['SalesService']['UpdatePaymentMethod'](arg1);
}
