// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['services']['UpdateService']['ApplyUpdate'](arg1);
}

export function CheckForUpdates() {
  return window['go']['services']['UpdateService']['CheckForUpdates']();
}

export function DownloadUpdate(arg1) {
  return window['go']['services']['UpdateService']['DownloadUpdate'](arg1);
}

export function ExtractUpdate(arg1) {
  return window['go']['services']['UpdateService']['ExtractUpdate'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['services']['UpdateService']['GetCurrentVersion']();
}

export function PerformUpdate() {
  return window['go']['services']['UpdateService']['PerformUpdate']();
}
