// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<services.UpdateInfo>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function ExtractUpdate(arg1:string):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function PerformUpdate():Promise<void>;
