// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {websocket} from '../models';

export function DisconnectClient(arg1:string):Promise<void>;

export function GetConnectedClients():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function SendTestNotification():Promise<void>;

export function SetServer(arg1:websocket.Server):Promise<void>;
