// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisconnectClient(arg1) {
  return window['go']['services']['WebSocketManagementService']['DisconnectClient'](arg1);
}

export function GetConnectedClients() {
  return window['go']['services']['WebSocketManagementService']['GetConnectedClients']();
}

export function GetStatus() {
  return window['go']['services']['WebSocketManagementService']['GetStatus']();
}

export function SendTestNotification() {
  return window['go']['services']['WebSocketManagementService']['SendTestNotification']();
}

export function SetServer(arg1) {
  return window['go']['services']['WebSocketManagementService']['SetServer'](arg1);
}
