// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectDatabaseWithConfig(arg1) {
  return window['go']['main']['App']['ConnectDatabaseWithConfig'](arg1);
}

export function InitializeServicesAfterSetup() {
  return window['go']['main']['App']['InitializeServicesAfterSetup']();
}
