name: Build and Release Wails App

on:
  push:
    tags:
      - 'v*'   # Solo se ejecuta cuando haces un tag tipo v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          cd ..

      - name: Build app for Windows
        run: wails build -clean -platform windows/amd64

      - name: Create release archive
        run: |
          cd build/bin
          Compress-Archive -Path RestaurantPOS.exe -DestinationPath ../../RestaurantPOS-Windows-x64.zip
          cd ../..
        shell: pwsh

      - name: Upload to public repo
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Restaurant POS System ${{ github.ref_name }}"
          body: |
            ## Restaurant POS System Release ${{ github.ref_name }}

            Sistema de Punto de Venta para Restaurantes con Facturación Electrónica DIAN (Colombia)

            ### 📦 Instalación
            1. Descargar `RestaurantPOS-Windows-x64.zip`
            2. Extraer el archivo `RestaurantPOS.exe`
            3. Ejecutar `RestaurantPOS.exe`
            4. Completar el Setup Wizard en el primer inicio

            ### ✅ Requisitos
            - Windows 10/11 (64-bit)
            - PostgreSQL 14+ (local o cloud)
            - WebView2 Runtime (se instala automáticamente si no está presente)
            - Cuenta en [FacturaLatam.com](https://facturalatam.com) para facturación electrónica DIAN

            ### 📖 Documentación
            Ver [README.md](https://github.com/DrewGGM/pos-app-wails/blob/main/README.md) para guía completa de instalación y configuración.

            ### 🔑 Credenciales por Defecto
            - Usuario: `admin`
            - Contraseña: `admin`
            - ⚠️ **Cambiar inmediatamente después del primer login**
          repository: DrewGGM/wails-posapp-releases
          token: ${{ secrets.RELEASE_TOKEN }}
          files: RestaurantPOS-Windows-x64.zip
